#pragma once

#include "../domain/Interfaces.hpp"
#include "../infrastructure/AppSettings.hpp"
#include "../infrastructure/StringUtils.hpp"
#include <memory>
#include <iostream>
#include <sstream>
#include <chrono>
#include <vector>
#include <string>
#include <set>

class BaseEcosystemHandler : public IEcosystemHandler {
protected:
    std::shared_ptr<IGitLabClient> gitlab;
    std::shared_ptr<IAICodeAssistant> ai;
    std::vector<DependencyMigration> migrations;

public:
    BaseEcosystemHandler(
        std::shared_ptr<IGitLabClient> glClient,
        std::shared_ptr<IAICodeAssistant> aiAssistant,
        const std::vector<DependencyMigration>& configMigrations)
        : gitlab(glClient), ai(aiAssistant), migrations(configMigrations) {}

    virtual ~BaseEcosystemHandler() = default;

protected:
    std::string GenerateBranchName(const std::string& ecosystemPrefix) const {
        auto now = std::chrono::system_clock::now().time_since_epoch().count();
        return "chore/deps-update-" + ecosystemPrefix + "-" + std::to_string(now);
    }

    void DeduplicateChanges(std::vector<DependencyChange>& changes) const {
        std::vector<DependencyChange> uniqueChanges;
        std::set<std::string> seenKeys;
        
        for (const auto& change : changes) {
            std::string key = change.oldDep.group + ":" + change.oldDep.name;
            if (seenKeys.find(key) == seenKeys.end()) {
                seenKeys.insert(key);
                uniqueChanges.push_back(change);
            }
        }
        changes = uniqueChanges;
    }

    std::string PostProcessCode(std::string code, const std::vector<DependencyChange>& changes) const {
        for (const auto& change : changes) {
            for (const auto& migration : migrations) {
                if (change.oldDep.group == migration.oldGroup &&
                    (migration.oldName.empty() || change.oldDep.name == migration.oldName)) {
                    for (const auto& rep : migration.replacements) {
                        code = StringUtils::ReplaceAll(code, rep.search, rep.replace); 
                    }
                }
            }
        }
        return code;
    }

    std::string BuildMergeRequestDescription(
        const std::vector<DependencyChange>& changes,
        const std::vector<std::string>& modifiedFiles,
        const std::vector<std::string>& modifiedBuildFiles) const 
    {
        std::ostringstream ss;
        ss << "## Automated " << GetEcosystemName() << " Dependency & Code Update\n\n";
        ss << "This Merge Request was automatically generated by the CLI tool using AI provider: **"
           << ai->GetProviderName() << "**.\n\n";

        ss << "### Updated Dependencies (" << changes.size() << ")\n\n";
        ss << "| Dependency | Old Version | New Version | Source / Notes |\n";
        ss << "| :--- | :--- | :--- | :--- |\n";
        for (const auto& change : changes) {
            std::string id = change.oldDep.group.empty() ? change.oldDep.name : (change.oldDep.group + ":" + change.oldDep.name);
            ss << "| `" << id << "` "
               << "| `" << change.oldDep.version << "` "
               << "| `" << change.newDep.version << "` "
               << "| ";

            if (change.skipAI) ss << "  *Internal Registry*";
            else if (change.hasPackageMove) ss << "  *Relocated to `" << change.newDep.group << ":" << change.newDep.name << "`*";
            else ss << "  *Public Registry*";

            if (!change.releaseNotes.empty() && !change.skipAI) ss << "   " << change.releaseNotes;
            ss << " |\n";
        }
        ss << "\n";

        ss << "### Build Configurations Updated\n\n";
        for (const auto& file : modifiedBuildFiles) {
            ss << "- [x] `" << file << "`\n";
        }
        ss << "\n";

        ss << "### Refactored Source Files (" << modifiedFiles.size() << ")\n\n";
        if (modifiedFiles.empty()) {
            ss << "_No source files required code modifications._\n\n";
        } else {
            ss << "The following source files were automatically refactored for API compatibility:\n\n";
            for (const auto& file : modifiedFiles) {
                ss << "- [x] `" << file << "`\n";
            }
            ss << "\n";
        }

        return ss.str();
    }
};