#pragma once

#include "../domain/Interfaces.hpp"
#include "../infrastructure/AppSettings.hpp"
#include "../infrastructure/StringUtils.hpp" 
#include <memory>
#include <iostream>
#include <sstream>
#include <chrono>
#include <vector>
#include <string>
#include <ctime>
#include <set>

class DependencyUpdateOrchestrator {
private:
    std::shared_ptr<IGitLabClient> gitlab;
    std::shared_ptr<IMavenRegistry> maven;
    std::shared_ptr<IAICodeAssistant> ai;
    std::shared_ptr<IGradleParser> parser;
    
    // NEW: .NET specific dependencies
    std::shared_ptr<IDotNetParser> dotnetParser;
    std::shared_ptr<INuGetRegistry> nugetRegistry;

    std::vector<DependencyMigration> migrations;
    bool debugMode;

    std::string PostProcessCode(std::string code, const std::vector<DependencyChange>& changes) {
        for (const auto& change : changes) {
            for (const auto& migration : migrations) {
                if (change.oldDep.group == migration.oldGroup &&
                    (migration.oldName.empty() || change.oldDep.name == migration.oldName)) {
                    for (const auto& rep : migration.replacements) {
                        code = StringUtils::ReplaceAll(code, rep.search, rep.replace); 
                    }
                }
            }
        }
        return code;
    }

    bool FileImportsDependency(const std::string& code, const DependencyChange& change, bool isDotNet = false) {
        if (isDotNet) {
            // TargetFramework affects the whole project, always return true to allow modern C# refactoring
            if (change.oldDep.name == "TargetFramework") return true;
            
            // Standard NuGet package name check
            if (code.find(change.oldDep.name) != std::string::npos) return true;
            return false;
        }

        // Java checks
        if (code.find(change.oldDep.group) != std::string::npos) return true;
        if (code.find(change.oldDep.name) != std::string::npos) return true;
        if (change.oldDep.group == "junit" && code.find("org.junit") != std::string::npos) return true;
        if (change.oldDep.name == "guava" && code.find("com.google.common") != std::string::npos) return true;
        if (change.oldDep.name == "jackson-databind" && code.find("com.fasterxml.jackson") != std::string::npos) return true;
        if (change.oldDep.name == "joda-time" && code.find("org.joda.time") != std::string::npos) return true;
        return false;
    }

    bool IsOlderThanOneMonth(const std::string& isoDate) {
        if (isoDate.size() < 10) return false;
        try {
            int year = std::stoi(isoDate.substr(0, 4));
            int month = std::stoi(isoDate.substr(5, 2));
            int day = std::stoi(isoDate.substr(8, 2));

            auto now = std::chrono::system_clock::now();
            time_t tt = std::chrono::system_clock::to_time_t(now);
            tm local_tm = *localtime(&tt);

            int currentYear = local_tm.tm_year + 1900;
            int currentMonth = local_tm.tm_mon + 1;
            int currentDay = local_tm.tm_mday;

            int totalMonthsDiff = (currentYear - year) * 12 + (currentMonth - month);
            
            if (totalMonthsDiff > 1) return true;
            if (totalMonthsDiff == 1) return currentDay >= day;
            return false;
        } catch (...) { return false; }
    }

    std::string BuildMergeRequestDescription(
        const std::vector<DependencyChange>& changes,
        const std::vector<std::string>& modifiedFiles,
        const std::vector<std::string>& modifiedBuildFiles,
        const std::string& ecosystem) 
    {
        std::ostringstream ss;
        ss << "## Automated " << ecosystem << " Dependency & Code Update\n\n";
        ss << "This Merge Request was automatically generated by the CLI tool using AI provider: **"
           << ai->GetProviderName() << "**.\n\n";

        ss << "### Updated Dependencies (" << changes.size() << ")\n\n";
        ss << "| Dependency | Old Version | New Version | Source / Notes |\n";
        ss << "| :--- | :--- | :--- | :--- |\n";
        for (const auto& change : changes) {
            std::string id = change.oldDep.group.empty() ? change.oldDep.name : (change.oldDep.group + ":" + change.oldDep.name);
            ss << "| `" << id << "` "
               << "| `" << change.oldDep.version << "` "
               << "| `" << change.newDep.version << "` "
               << "| ";

            if (change.skipAI) ss << "  *Internal Registry*";
            else if (change.hasPackageMove) ss << "  *Relocated to `" << change.newDep.group << ":" << change.newDep.name << "`*";
            else ss << "  *Public Registry*";

            if (!change.releaseNotes.empty() && !change.skipAI) ss << "   " << change.releaseNotes;
            ss << " |\n";
        }
        ss << "\n";

        ss << "### Build Configurations Updated\n\n";
        for (const auto& file : modifiedBuildFiles) {
            ss << "- [x] `" << file << "`\n";
        }
        ss << "\n";

        ss << "### Refactored Source Files (" << modifiedFiles.size() << ")\n\n";
        if (modifiedFiles.empty()) {
            ss << "_No source files required code modifications._\n\n";
        } else {
            ss << "The following source files were automatically refactored for API compatibility:\n\n";
            for (const auto& file : modifiedFiles) {
                ss << "- [x] `" << file << "`\n";
            }
            ss << "\n";
        }

        return ss.str();
    }

    void DeduplicateChanges(std::vector<DependencyChange>& changes) {
        std::vector<DependencyChange> uniqueChanges;
        std::set<std::string> seenKeys;
        
        for (const auto& change : changes) {
            std::string key = change.oldDep.group + ":" + change.oldDep.name;
            if (seenKeys.find(key) == seenKeys.end()) {
                seenKeys.insert(key);
                uniqueChanges.push_back(change);
            }
        }
        changes = uniqueChanges;
    }

public:
    DependencyUpdateOrchestrator(
        std::shared_ptr<IGitLabClient> glClient,
        std::shared_ptr<IMavenRegistry> mvnRegistry,
        std::shared_ptr<IAICodeAssistant> aiAssistant,
        std::shared_ptr<IGradleParser> gradleParser,
        std::shared_ptr<IDotNetParser> dnParser,
        std::shared_ptr<INuGetRegistry> nugetReg,
        const std::vector<DependencyMigration>& configMigrations,
        bool isDebug = false)
        : gitlab(glClient), maven(mvnRegistry), ai(aiAssistant), parser(gradleParser),
          dotnetParser(dnParser), nugetRegistry(nugetReg), 
          migrations(configMigrations), debugMode(isDebug) {}

    void RunWorkflow(const std::string& gitlabGroupId) {
        std::cout << "Starting Multi-Ecosystem Dependency Update Workflow...\n";
        auto projects = gitlab->GetProjectsInGroup(gitlabGroupId);
        std::cout << "Found " << projects.size() << " projects in group " << gitlabGroupId << ".\n";
        
        for (const auto& project : projects) {
            ProcessProject(project);
        }
    }

private:
    void ProcessProject(const ProjectContext& project) {
        std::cout << "--------------------------------------------------\n";
        std::cout << "Processing Project: " << project.projectName << "\n";
        
        auto openMrs = gitlab->GetOpenMergeRequests(project.projectId);
        std::vector<MergeRequest> ourMrs;
        for (const auto& mr : openMrs) {
            if (mr.sourceBranch.find("chore/deps-update-") == 0) ourMrs.push_back(mr);
        }

        for (const auto& mr : ourMrs) {
            if (!IsOlderThanOneMonth(mr.createdAt)) {
                std::cout << "   Found recent active MR. Skipping project.\n";
                return; 
            }
        }

        for (const auto& mr : ourMrs) {
            std::cout << "  Closing stale MR (" << mr.sourceBranch << ")...\n";
            gitlab->CloseMergeRequest(project.projectId, mr.iid);
            gitlab->DeleteBranch(project.projectId, mr.sourceBranch);
        }

        std::cout << "Fetching full repository tree...\n";
        auto allFiles = gitlab->GetSourceFiles(project.projectId, project.defaultBranch);
        
        if (allFiles.empty()) {
            std::cout << "No files found in repository. Skipping.\n";
            return;
        }

        std::vector<std::string> gradleFiles;
        std::vector<std::string> javaSourceFiles;
        
        std::string slnxFilePath = "";
        std::vector<std::string> dotnetProjectFiles;
        std::vector<std::string> csharpSourceFiles;

        for (const auto& file : allFiles) {
            if (file.ends_with("build.gradle") || file.ends_with("build.gradle.kts") || file.ends_with("gradle.properties")) {
                gradleFiles.push_back(file);
            } else if (file.ends_with(".java") || file.ends_with(".kt")) {
                javaSourceFiles.push_back(file);
            } else if (file.ends_with(".slnx")) {
                slnxFilePath = file;
            } else if (file.ends_with(".csproj") || file.ends_with(".fsproj")) {
                dotnetProjectFiles.push_back(file);
            } else if (file.ends_with(".cs") || file.ends_with(".fs")) {
                csharpSourceFiles.push_back(file);
            }
        }

        // --- 1. Execute Java/Gradle Workflow ---
        if (!gradleFiles.empty()) {
            ProcessJavaEcosystem(project, gradleFiles, javaSourceFiles);
        }

        // --- 2. Execute .NET Workflow ---
        if (!slnxFilePath.empty()) {
            std::cout << "Detected .slnx solution: " << slnxFilePath << "\n";
            std::string slnxContent = gitlab->FetchFileContent(project.projectId, slnxFilePath, project.defaultBranch);
            
            std::vector<std::string> targetProjects = dotnetParser->ParseSlnxProjects(slnxContent);
            ProcessDotNetEcosystem(project, targetProjects, csharpSourceFiles, slnxFilePath);
        } 
        else if (!dotnetProjectFiles.empty()) {
            std::cout << "No .slnx found. Managing discovered .csproj files independently.\n";
            ProcessDotNetEcosystem(project, dotnetProjectFiles, csharpSourceFiles, "");
        }
    }

    void ProcessJavaEcosystem(const ProjectContext& project, const std::vector<std::string>& buildFiles, const std::vector<std::string>& sourceFiles) {
        std::vector<DependencyChange> masterChanges;
        std::vector<std::string> modifiedBuildFiles;
        
        auto now = std::chrono::system_clock::now().time_since_epoch().count();
        std::string branchName = "chore/deps-update-java-" + std::to_string(now);
        bool branchCreated = false;

        for (const auto& buildFilePath : buildFiles) {
            std::string buildContent = gitlab->FetchFileContent(project.projectId, buildFilePath, project.defaultBranch);
            if (buildContent.empty()) continue;

            auto dependencies = parser->ParseDependencies(buildContent);
            std::string updatedContent = buildContent;
            bool fileChanged = false;

            for (const auto& dep : dependencies) {
                auto latestOpt = maven->GetLatestVersion(dep);
                if (latestOpt && *latestOpt != dep.version) {
                    Dependency newDep = {dep.group, dep.name, *latestOpt};
                    DependencyChange diff = maven->InspectVersionDiff(dep, newDep);
                    updatedContent = parser->UpdateDependencyVersion(updatedContent, dep, diff.newDep);
                    masterChanges.push_back(diff);
                    fileChanged = true;
                    
                    std::cout << "Java Update found in " << buildFilePath << ": " << dep.name << " (" << dep.version << " -> " << diff.newDep.version << ")\n";
                }
            }

            if (fileChanged && updatedContent != buildContent) {
                if (!branchCreated) {
                    try { gitlab->CreateBranch(project.projectId, branchName, project.defaultBranch); branchCreated = true; } 
                    catch (...) { return; }
                }
                gitlab->CommitFile(project.projectId, branchName, buildFilePath, updatedContent, "chore: Update Java dependencies in " + buildFilePath);
                modifiedBuildFiles.push_back(buildFilePath);
            }
        }

        if (masterChanges.empty() || !branchCreated) return;

        DeduplicateChanges(masterChanges);
        std::vector<std::string> modifiedSourceFiles;

        for (const auto& filePath : sourceFiles) {
            std::string baseCode = gitlab->FetchFileContent(project.projectId, filePath, project.defaultBranch);
            if (baseCode.empty()) continue;

            std::vector<DependencyChange> relevantChanges;
            for (const auto& change : masterChanges) {
                if (FileImportsDependency(baseCode, change, false) && !change.skipAI) {
                    relevantChanges.push_back(change);
                }
            }

            if (relevantChanges.empty()) continue;

            DependencyChange combinedChange;
            combinedChange.oldDep = {"Multiple", "Dependencies", "Various"};
            combinedChange.newDep.version = "Various";
            
            std::string combinedNotes = "TASK: Refactor Java/Kotlin code to be compatible with updated dependencies:\n";
            for (const auto& c : relevantChanges) {
                combinedNotes += "- " + c.oldDep.group + ":" + c.oldDep.name + " updated to " + c.newDep.version + "\n";
            }
            
            combinedNotes += "\nOUTPUT FORMAT: Return ONLY the raw updated source code. DO NOT wrap in ```java markdown blocks.";
            combinedChange.releaseNotes = combinedNotes;

            std::cout << " -> AI analyzing Java file " << filePath << "...\n";
            RefactorRequest req = {filePath, baseCode, combinedChange, ""};
            std::string rawAiCode = ai->RefactorCode(req);
            
            std::string workingCode = StringUtils::CleanAIOutput(rawAiCode, baseCode);
            workingCode = PostProcessCode(workingCode, relevantChanges);

            if (workingCode != baseCode) {
                gitlab->CommitFile(project.projectId, branchName, filePath, workingCode, "refactor: AI updates for Java dependency upgrades");
                modifiedSourceFiles.push_back(filePath);
            }
        }

        std::string mrDescription = BuildMergeRequestDescription(masterChanges, modifiedSourceFiles, modifiedBuildFiles, "Java/Kotlin");
        gitlab->CreateMergeRequest(project.projectId, branchName, project.defaultBranch, "chore: Automated Java Dependency Update", mrDescription);
    }

    void ProcessDotNetEcosystem(const ProjectContext& project, const std::vector<std::string>& projectFiles, const std::vector<std::string>& sourceFiles, const std::string& slnxFile) {
        std::vector<DependencyChange> masterChanges;
        std::vector<std::string> modifiedBuildFiles;
        
        auto now = std::chrono::system_clock::now().time_since_epoch().count();
        std::string branchName = "chore/deps-update-dotnet-" + std::to_string(now);
        bool branchCreated = false;

        for (const auto& projPath : projectFiles) {
            std::string content = gitlab->FetchFileContent(project.projectId, projPath, project.defaultBranch);
            if (content.empty()) continue;

            auto dependencies = dotnetParser->ParseDependencies(content);
            std::string updatedContent = content;
            bool fileChanged = false;

            for (const auto& dep : dependencies) {
                if (dep.name == "TargetFramework") {
                    if (dep.version.starts_with("net") && dep.version != "net10.0") {
                        Dependency newDep = {"Microsoft.NETCore.App", "TargetFramework", "net10.0"};
                        updatedContent = dotnetParser->UpdateDependencyVersion(updatedContent, dep, newDep);
                        
                        DependencyChange diff = {dep, newDep, false, "", "", "Upgraded to .NET 10 LTS.", false};
                        masterChanges.push_back(diff);
                        fileChanged = true;
                        std::cout << "Framework Update found in " << projPath << ": " << dep.version << " -> net10.0\n";
                    }
                    continue;
                }

                auto latestOpt = nugetRegistry->GetLatestVersion(dep);
                if (latestOpt && *latestOpt != dep.version) {
                    Dependency newDep = {dep.group, dep.name, *latestOpt};
                    DependencyChange diff = nugetRegistry->InspectVersionDiff(dep, newDep);
                    
                    updatedContent = dotnetParser->UpdateDependencyVersion(updatedContent, dep, diff.newDep);
                    masterChanges.push_back(diff);
                    fileChanged = true;
                    std::cout << "NuGet Update found in " << projPath << ": " << dep.name << " (" << dep.version << " -> " << diff.newDep.version << ")\n";
                }
            }

            if (fileChanged && updatedContent != content) {
                if (!branchCreated) {
                    try { gitlab->CreateBranch(project.projectId, branchName, project.defaultBranch); branchCreated = true; } 
                    catch (...) { return; }
                }
                gitlab->CommitFile(project.projectId, branchName, projPath, updatedContent, "chore: Update .NET dependencies in " + projPath);
                modifiedBuildFiles.push_back(projPath);
            }
        }

        if (masterChanges.empty() || !branchCreated) return;

        DeduplicateChanges(masterChanges);
        std::vector<std::string> modifiedSourceFiles;

        for (const auto& filePath : sourceFiles) {
            std::string baseCode = gitlab->FetchFileContent(project.projectId, filePath, project.defaultBranch);
            if (baseCode.empty()) continue;

            std::vector<DependencyChange> relevantChanges;
            bool isFrameworkUpgrade = false;
            
            for (const auto& change : masterChanges) {
                if (FileImportsDependency(baseCode, change, true) && !change.skipAI) {
                    relevantChanges.push_back(change);
                    if (change.oldDep.name == "TargetFramework") isFrameworkUpgrade = true;
                }
            }

            if (relevantChanges.empty()) continue;

            DependencyChange combinedChange;
            combinedChange.oldDep = {"Multiple", "NuGet Packages", "Various"};
            combinedChange.newDep.version = "Various";
            
            std::string combinedNotes = "TASK: Refactor C#/F# code to be compatible with updated dependencies:\n";
            for (const auto& c : relevantChanges) {
                if (c.oldDep.name == "TargetFramework") {
                    combinedNotes += "- TargetFramework upgraded to .NET 10. Refactor syntax to utilize modern C# language features if applicable.\n";
                } else {
                    combinedNotes += "- " + c.oldDep.name + " updated to " + c.newDep.version + "\n";
                }
            }
            
            combinedNotes += "\nOUTPUT FORMAT: Return ONLY the raw updated source code. DO NOT wrap in ```csharp markdown blocks.";
            combinedChange.releaseNotes = combinedNotes;

            std::cout << " -> AI analyzing .NET file " << filePath << "...\n";
            RefactorRequest req = {filePath, baseCode, combinedChange, ""};
            std::string rawAiCode = ai->RefactorCode(req);
            
            std::string workingCode = StringUtils::CleanAIOutput(rawAiCode, baseCode);

            if (workingCode != baseCode) {
                gitlab->CommitFile(project.projectId, branchName, filePath, workingCode, "refactor: AI updates for .NET upgrades");
                modifiedSourceFiles.push_back(filePath);
            }
        }

        if (!slnxFile.empty()) {
            modifiedBuildFiles.push_back(slnxFile + " (Scanned via Solution)");
        }

        std::string mrDescription = BuildMergeRequestDescription(masterChanges, modifiedSourceFiles, modifiedBuildFiles, ".NET");
        gitlab->CreateMergeRequest(project.projectId, branchName, project.defaultBranch, "chore: Automated .NET Dependency Update", mrDescription);
    }
};