#pragma once

#include "../domain/Interfaces.hpp"
#include "../infrastructure/AppSettings.hpp"
#include <memory>
#include <iostream>
#include <sstream>
#include <chrono>
#include <vector>
#include <string>
#include <ctime>
#include <set>

class DependencyUpdateOrchestrator {
private:
    std::shared_ptr<IGitLabClient> gitlab;
    std::shared_ptr<IMavenRegistry> maven;
    std::shared_ptr<IAICodeAssistant> ai;
    std::shared_ptr<IGradleParser> parser;
    std::vector<DependencyMigration> migrations;
    bool debugMode;

    std::string ReplaceAll(std::string str, const std::string& from, const std::string& to) {
        if (from.empty()) return str;
        size_t start_pos = 0;
        while((start_pos = str.find(from, start_pos)) != std::string::npos) {
            str.replace(start_pos, from.length(), to);
            start_pos += to.length(); 
        }
        return str;
    }

    std::string CleanAIOutput(std::string code, const std::string& baseCode) {
        size_t startTick = code.find("```");
        if (startTick != std::string::npos) {
            size_t startLineEnd = code.find('\n', startTick);
            size_t endTick = code.rfind("```");
            if (endTick != std::string::npos && endTick > startLineEnd) {
                code = code.substr(startLineEnd + 1, endTick - startLineEnd - 1);
            }
        }
        
        if (code.length() < (baseCode.length() * 0.5)) return baseCode; 
        return code;
    }

    // Dynamic, Data-Driven Post Processor
    std::string PostProcessCode(std::string code, const std::vector<DependencyChange>& changes) {
        for (const auto& change : changes) {
            for (const auto& migration : migrations) {
                if (change.oldDep.group == migration.oldGroup && 
                   (migration.oldName.empty() || change.oldDep.name == migration.oldName)) {
                    for (const auto& rep : migration.replacements) {
                        code = ReplaceAll(code, rep.search, rep.replace);
                    }
                }
            }
        }
        return code;
    }

    bool FileImportsDependency(const std::string& code, const DependencyChange& change) {
        if (code.find(change.oldDep.group) != std::string::npos) return true;
        if (code.find(change.oldDep.name) != std::string::npos) return true;
        if (change.oldDep.group == "junit" && code.find("org.junit") != std::string::npos) return true;
        if (change.oldDep.name == "guava" && code.find("com.google.common") != std::string::npos) return true;
        if (change.oldDep.name == "jackson-databind" && code.find("com.fasterxml.jackson") != std::string::npos) return true;
        if (change.oldDep.name == "joda-time" && code.find("org.joda.time") != std::string::npos) return true;
        return false;
    }

    bool IsOlderThanOneMonth(const std::string& isoDate) {
        if (isoDate.size() < 10) return false;
        try {
            int year = std::stoi(isoDate.substr(0, 4));
            int month = std::stoi(isoDate.substr(5, 2));
            int day = std::stoi(isoDate.substr(8, 2));

            auto now = std::chrono::system_clock::now();
            time_t tt = std::chrono::system_clock::to_time_t(now);
            tm local_tm = *localtime(&tt);

            int currentYear = local_tm.tm_year + 1900;
            int currentMonth = local_tm.tm_mon + 1;
            int currentDay = local_tm.tm_mday;

            int totalMonthsDiff = (currentYear - year) * 12 + (currentMonth - month);
            
            if (totalMonthsDiff > 1) return true;
            if (totalMonthsDiff == 1) return currentDay >= day;
            return false;
        } catch (...) { return false; }
    }

    std::string BuildMergeRequestDescription(
        const std::vector<DependencyChange>& changes,
        const std::vector<std::string>& modifiedFiles,
        const std::vector<std::string>& modifiedBuildFiles) {
        
        std::ostringstream ss;
        ss << "## 🤖 Automated Dependency & Code Update\n\n";
        ss << "This Merge Request was automatically generated by the **Gradle Dependency Updater** CLI tool using AI provider: **" 
           << ai->GetProviderName() << "**.\n\n";

        ss << "### 📦 Updated Dependencies (" << changes.size() << ")\n\n";
        ss << "| Dependency | Old Version | New Version | Source / Notes |\n";
        ss << "| :--- | :--- | :--- | :--- |\n";
        for (const auto& change : changes) {
            ss << "| `" << change.oldDep.group << ":" << change.oldDep.name << "` "
               << "| `" << change.oldDep.version << "` "
               << "| `" << change.newDep.version << "` "
               << "| ";
            if (change.skipAI) ss << "🔒 *Internal GitLab Registry*";
            else if (change.hasPackageMove) ss << "⚠️ *Relocated to `" << change.newDep.group << ":" << change.newDep.name << "`*";
            else ss << "✅ *Maven Central*";

            if (!change.releaseNotes.empty() && !change.skipAI) ss << " — " << change.releaseNotes;
            ss << " |\n";
        }
        ss << "\n";

        ss << "### 📄 Build Configurations Updated\n\n";
        for (const auto& file : modifiedBuildFiles) {
            ss << "- [x] `" << file << "`\n";
        }
        ss << "\n";

        ss << "### 🛠️ Refactored Source Files (" << modifiedFiles.size() << ")\n\n";
        if (modifiedFiles.empty()) {
            ss << "_No Java/Kotlin source files required code modifications._\n\n";
        } else {
            ss << "The following source files were automatically refactored for API compatibility:\n\n";
            for (const auto& file : modifiedFiles) {
                ss << "- [x] `" << file << "`\n";
            }
            ss << "\n";
        }

        return ss.str();
    }

    // Helper to deduplicate changes (since submodules might update the same library)
    void DeduplicateChanges(std::vector<DependencyChange>& changes) {
        std::vector<DependencyChange> uniqueChanges;
        std::set<std::string> seenKeys;
        
        for (const auto& change : changes) {
            std::string key = change.oldDep.group + ":" + change.oldDep.name;
            if (seenKeys.find(key) == seenKeys.end()) {
                seenKeys.insert(key);
                uniqueChanges.push_back(change);
            }
        }
        changes = uniqueChanges;
    }

public:
    DependencyUpdateOrchestrator(
        std::shared_ptr<IGitLabClient> glClient,
        std::shared_ptr<IMavenRegistry> mvnRegistry,
        std::shared_ptr<IAICodeAssistant> aiAssistant,
        std::shared_ptr<IGradleParser> gradleParser,
        const std::vector<DependencyMigration>& configMigrations,
        bool isDebug = false)
        : gitlab(glClient), maven(mvnRegistry), ai(aiAssistant), parser(gradleParser), 
          migrations(configMigrations), debugMode(isDebug) {}

    void RunWorkflow(const std::string& gitlabGroupId) {
        std::cout << "Starting Multi-Module Dependency Update Workflow...\n";
        auto projects = gitlab->GetProjectsInGroup(gitlabGroupId);
        std::cout << "Found " << projects.size() << " projects in group " << gitlabGroupId << ".\n";

        for (const auto& project : projects) {
            ProcessProject(project);
        }
    }

private:
    void ProcessProject(const ProjectContext& project) {
        std::cout << "--------------------------------------------------\n";
        std::cout << "Processing Project: " << project.projectName << "\n";

        auto openMrs = gitlab->GetOpenMergeRequests(project.projectId);
        std::vector<MergeRequest> ourMrs;
        for (const auto& mr : openMrs) {
            if (mr.sourceBranch.find("chore/deps-update-") == 0) ourMrs.push_back(mr);
        }
        for (const auto& mr : ourMrs) {
            if (!IsOlderThanOneMonth(mr.createdAt)) {
                std::cout << "⏭️  Found recent active MR. Skipping project.\n";
                return; 
            }
        }
        for (const auto& mr : ourMrs) {
            std::cout << "🧹 Closing stale MR (" << mr.sourceBranch << ")...\n";
            gitlab->CloseMergeRequest(project.projectId, mr.iid);
            gitlab->DeleteBranch(project.projectId, mr.sourceBranch);
        }

        std::cout << "Fetching full repository tree...\n";
        auto allFiles = gitlab->GetSourceFiles(project.projectId, project.defaultBranch);
        if (allFiles.empty()) {
            std::cout << "No files found in repository. Skipping.\n";
            return;
        }

        std::vector<std::string> buildFiles;
        std::vector<std::string> sourceFiles;
        
        for (const auto& file : allFiles) {
            if (file.ends_with("build.gradle") || file.ends_with("build.gradle.kts") || file.ends_with("gradle.properties")) {
                buildFiles.push_back(file);
            } else if (file.ends_with(".java") || file.ends_with(".kt")) {
                sourceFiles.push_back(file);
            }
        }

        if (buildFiles.empty()) {
            std::cout << "No Gradle build files found. Skipping.\n";
            return;
        }

        std::vector<DependencyChange> masterChanges;
        std::vector<std::string> modifiedBuildFiles;

        auto now = std::chrono::system_clock::now().time_since_epoch().count();
        std::string branchName = "chore/deps-update-" + std::to_string(now);
        bool branchCreated = false;

        // 1. PROCESS ALL BUILD FILES IN ALL MODULES
        for (const auto& buildFilePath : buildFiles) {
            std::string buildContent = gitlab->FetchFileContent(project.projectId, buildFilePath, project.defaultBranch);
            if (buildContent.empty()) continue;

            auto dependencies = parser->ParseDependencies(buildContent);
            std::string updatedContent = buildContent;
            bool fileChanged = false;

            for (const auto& dep : dependencies) {
                auto latestOpt = maven->GetLatestVersion(dep);
                if (latestOpt && *latestOpt != dep.version) {
                    Dependency newDep = {dep.group, dep.name, *latestOpt};
                    DependencyChange diff = maven->InspectVersionDiff(dep, newDep);
                    updatedContent = parser->UpdateDependencyVersion(updatedContent, dep, diff.newDep);
                    masterChanges.push_back(diff);
                    fileChanged = true;
                    
                    if (diff.hasPackageMove) {
                        std::cout << "Migration found in " << buildFilePath << ": " << dep.name << " (" << dep.version << ") -> " << diff.newDep.group << ":" << diff.newDep.name << " (" << diff.newDep.version << ")\n";
                    } else {
                        std::cout << "Update found in " << buildFilePath << ": " << dep.name << " (" << dep.version << " -> " << diff.newDep.version << ")\n";
                    }
                }
            }

            if (fileChanged && updatedContent != buildContent) {
                if (!branchCreated) {
                    try {
                        std::cout << "Creating branch: " << branchName << "\n";
                        gitlab->CreateBranch(project.projectId, branchName, project.defaultBranch);
                        branchCreated = true;
                    } catch (const std::exception& e) {
                        std::cerr << "🚫 Git operation failed for project '" << project.projectName << "'. Skipping. Reason: " << e.what() << "\n";
                        return; 
                    }
                }

                try {
                    gitlab->CommitFile(project.projectId, branchName, buildFilePath, updatedContent, "chore: Update dependencies in " + buildFilePath);
                    modifiedBuildFiles.push_back(buildFilePath);
                } catch (const std::exception& e) {
                    std::cerr << "🚫 Failed to commit build file '" << buildFilePath << "'.\n";
                }
            }
        }

        if (masterChanges.empty() || !branchCreated) {
            std::cout << "All dependencies across all modules are up to date.\n";
            return;
        }

        DeduplicateChanges(masterChanges);
        std::vector<std::string> modifiedSourceFiles;

        std::cout << "Found " << sourceFiles.size() << " source files. Beginning Multi-Module AI refactoring...\n";

        // 2. PROCESS ALL SOURCE FILES ACROSS ALL MODULES
        for (const auto& filePath : sourceFiles) {
            std::string baseCode = gitlab->FetchFileContent(project.projectId, filePath, project.defaultBranch);
            if (baseCode.empty()) continue;

            std::vector<DependencyChange> relevantChanges;
            for (const auto& change : masterChanges) {
                if (FileImportsDependency(baseCode, change)) {
                    if (!change.skipAI) relevantChanges.push_back(change);
                }
            }

            if (relevantChanges.empty()) continue;

            DependencyChange combinedChange;
            combinedChange.oldDep.group = "Multiple";
            combinedChange.oldDep.name = "Dependencies";
            combinedChange.oldDep.version = "Various";
            combinedChange.newDep.version = "Various";
            
            std::string combinedNotes = "TASK: Refactor the provided Java/Kotlin code to be compatible with these updated dependencies:\n";
            for (const auto& c : relevantChanges) {
                if (c.hasPackageMove) {
                    combinedNotes += "- " + c.oldDep.group + ":" + c.oldDep.name + " -> RELOCATED TO " + c.newDep.group + ":" + c.newDep.name + "\n";
                } else {
                    combinedNotes += "- " + c.oldDep.group + ":" + c.oldDep.name + " updated to " + c.newDep.version + "\n";
                }
            }
            
            combinedNotes += "\nCRITICAL STRUCTURAL MIGRATION RULES:\n";
            combinedNotes += "1. If migrating JUnit 4 to JUnit 5, rewrite any `@Test(expected = Exception.class)` annotations to use `assertThrows(Exception.class, () -> { ... });` inside the method body.\n";
            combinedNotes += "\nOUTPUT FORMAT:\n";
            combinedNotes += "Return ONLY the raw updated source code. DO NOT wrap in ```java markdown blocks. DO NOT add conversational text.";
            combinedChange.releaseNotes = combinedNotes;

            std::cout << " -> AI analyzing " << filePath << " for " << relevantChanges.size() << " updates...\n";

            RefactorRequest req = {filePath, baseCode, combinedChange, ""};
            std::string rawAiCode = ai->RefactorCode(req);
            
            std::string workingCode = CleanAIOutput(rawAiCode, baseCode);
            workingCode = PostProcessCode(workingCode, relevantChanges); // Apply appsettings.json rules!

            if (workingCode != baseCode) {
                if (debugMode) {
                    std::cout << "\n=======================================================\n";
                    std::cout << "🔍 [DEBUG] Original File: " << filePath << "\n";
                    std::cout << "#######################################################\n";
                    std::cout << baseCode << "\n";
                    std::cout << "#######################################################\n\n";
                }

                try {
                    std::cout << "AI refactored file: " << filePath << "\n";
                    gitlab->CommitFile(project.projectId, branchName, filePath, workingCode, "refactor: AI updates for dependency upgrades");
                    modifiedSourceFiles.push_back(filePath);
                } catch (const std::exception& e) {
                    std::cerr << "🚫 Failed to commit refactored file '" << filePath << "': " << e.what() << "\n";
                }
            }
        }

        try {
            std::string mrDescription = BuildMergeRequestDescription(masterChanges, modifiedSourceFiles, modifiedBuildFiles);
            std::string mrUrl = gitlab->CreateMergeRequest(project.projectId, branchName, project.defaultBranch, "chore: Automated Dependency & Code Update", mrDescription);
            std::cout << "Successfully created Merge Request: " << mrUrl << "\n";
        } catch (const std::exception& e) {
            std::cerr << "🚫 Failed to create Merge Request: " << e.what() << "\n";
        }
    }
};